from sqlalchemy.orm import Session

from . import models, schemas


# 操作数据库：添加文案
def create_writing(db: Session, writing: schemas.WritingCreate):
    db_writing = models.Writing(prompt=writing.prompt, answser=writing.answer)
    db.add(db_writing)
    db.commit()
    # db.refresh : commonly used with fields that are automatically generated by the database
    # here, after committing db_writing to the database, some fields \
    # (like the primary key, if it's auto-incremented) will have new values that were generated by the database. \
    # db.refresh(db_writing) updates the db_writing object with these new values from the database.
    db.refresh(db_writing)
    return db_writing


# 操作数据库：获取所有文案
def get_writings(db: Session, skip: int = 0, limit: int = 100):
    return db.query(models.Writing).offset(skip).limit(limit).all()


# 操作数据库：删除文案
def delete_writing(db: Session, id: int):
    writing = db.get(models.Writing, id)
    db.delete(writing)
    db.commit()
    return {"ok": True}


# 更多session API
# 参考：https://docs.sqlalchemy.org/en/20/orm/session_api.html#sqlalchemy.orm.Session
